@startgantt

'Example Gantt chart
'For documentation see https://plantuml.com/gantt-diagram

Project starts 2021-06-01
[Prototype design] lasts 4 weeks
[Prototype design] is 40% completed
[Prototype design] is colored in LightBlue/Black
[Code prototype] lasts 10 days
[Write tests] lasts 5 days

[Code prototype] starts at [Prototype design]'s end
[Write tests] starts at [Code prototype]'s start

@endgantt
